### Ir a la pagina principal
http://localhost:3008

### Mostrar todos los componentes
http://localhost:3008/productos
### Mostrar los productos de una cierta categoría(con o sin tildes) y aceptando minúsculas
GET http://localhost:3008/productos?categoria=portátil
### Mostrar un producto por id
GET http://localhost:3008/productos/6668f9a4a0b12b2fbfc6e6f3

### Agregar un producto
POST http://localhost:3008/productos/
content-type: application/json

{
    "nombre": "Nuevo Producto",
    "importe": 250000,
    "categoria": "Smartphone"
}
### Borrar un producto por id
DELETE http://localhost:3008/productos/6668f9a4a0b12b2fbfc6e6f3

### Modificar/Actualizar un producto parcialmente
PATCH http://localhost:3008/productos/666b24be293bd36cddda64b9
content-type: application/json

{
    "importe": 200000
}
### Modificar/Actualizar un producto completamente
PUT http://localhost:3008/productos/666b24be293bd36cddda64b9
content-type: application/json

{
    "nombre": "Producto Actualizado",
    "importe": 300000,
    "categoria": "Tablet"
}
### Obtener los productos con un importe mayor al especificado.

GET http://localhost:3008/productos/importes/mayor/200000

### Obtener los productos con un importe menor al especificado.

GET http://localhost:3008/productos/importes/menor/200000

### Obtener lista  de todas categorias de componentes

GET http://localhost:3008/productos/categoria

### Buscar productos por nombre total o parcial,incluye minúsculas
GET http://localhost:3008/productos/nombre/m



### Obtener productos por rango de precio
GET http://localhost:3008/productos/rango/1000/100000